### ISSUE TITLE
Cannot index into a null array.

### ISSUE THREAD

**Issue by Aldo-f** [okibcn/wslcompact#8] opened 2023-02-15 09:17 UTC
Using ` WslCompact v8.0 2023.02.13`

```
PS C:\Users\myName> wslcompact
 WslCompact v8.0 2023.02.13
 (C) 2023 Oscar Lopez
 wslcompact -h for help. For more information visit: https://github.com/okibcn/wslcompact

 Distro's name:  Ubuntu-18.04
 Image file:     C:\Users\myName\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\ext4.vhdx
 Current size:   15193 MB
Cannot index into a null array.
At C:\Users\myName\scoop\apps\wslcompact\current\wslcompact.ps1:79 char:17
+ ...             $estimated = ((wsl --system -d "$wsl_distro" -e df /mnt/w ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

 Estimated size: 0 +/- 0 MB
 The estimated process time using an SSD is about 0 minutes.
```

**Comment by okibcn** [comment] 2023-02-15 20:19
It is a duplicate of issue #7. Please continue the conversation there.

**Closed by okibcn** 2023-02-15 20:19 UTC
